export const findAllUsers = async(req,res) => {
    try {

    }catch (error){
        return res.status(500).json({
            status: 'fail',
            message: 'Sometihing went very wrong! '
        })
    }
}
export const createUser = async(req,res) => {
    try {

    }catch (error){
        return res.status(500).json({
            status: 'fail',
            message: 'Sometihing went very wrong! '
        })
    }
}
export const findOneUser = async(req,res) => {
    try {

    }catch (error){
        return res.status(500).json({
            status: 'fail',
            message: 'Sometihing went very wrong! '
        })
    }
}
export const updateUser = async(req,res) => {
    try {

    }catch (error){
        return res.status(500).json({
            status: 'fail',
            message: 'Sometihing went very wrong! '
        })
    }
}
export const deleteUser = async(req,res) => {
    try {

    }catch (error){
        return res.status(500).json({
            status: 'fail',
            message: 'Sometihing went very wrong! '
        })
    }
}